export const countryCodes = {
    AZE: 'Azerbajdzsán',
    AUT: 'Ausztria',
    'BA-SRP': 'Bosznia-hercegovinai Szerb Köztársaság',
    BGR: 'Bulgária',
    BIH: 'Bosznia-Hercegovina',
    CZE: 'Csehország',
    EGY: 'Egyiptom',
    HUN: 'Magyarország',
    KAZ: 'Kazahsztán',
    KGZ: 'Kirgizisztán',
    QAT: 'Katar',
    'RU-TA': 'Tatárföld',
    SRB: 'Szerbia',
    SVN: 'Szlovénia',
    TKM: 'Türkmenisztán',
    TUR: 'Törökország',
    UZB: 'Üzbegisztán',
  };